### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by MiLeG** [dfm/Star-Field#28]
Hi,
I'm interested in this project and was wondering if you could add a license to it, just to define the terms and conditions for the usage of this code. As [this page](https://choosealicense.com/no-permission/) suggests it's best to request a license added to a project than to use unlicensed code at all.

**Comment by eggplantbren** [comment]
Check out eggplantbren/StarStudded which does have a license.

**Comment by eggplantbren** [comment]
I've added the MIT license in case you really want to use this. I've also put a note in the readme saying that StarStudded supersedes the code here (IMHO). Closed with commit 59c1a19934341237cad07c582e6f0c65bd289b9b
